[package]
name = "minion"
version = "0.1.0"
authors = ["Erich Cordoba <erich.cm@yandex.com>"]

[dependencies]
tokio-core = "*"
tokio-timer = "*"
futures = "*"
futures-cpupool = "*"
walkdir = "*"
regex = "0.2"
zmq = "0.8"