apiVersion: v1
kind: Pod
metadata:
  name: minion-client
  labels:
    purpose: Run-minions
spec:
  containers:
  - name: minion
    image: minion-client:latest
    imagePullPolicy: IfNotPresent
  restartPolicy: OnFailure
